    # 1. Update config values in config.development.json
    # 2. Set APP_ENV environment variable to proper value in Dockerfile-redis (default is "development")
    #    export APP_ENV=development
    # 3. Run docker-compose build
    # 4. Run docker-compose up
    # 5. Live long and prosper
    
version: "2"
 
services:
    jira-node-server:
      container_name: jira-node-server
      build: 
        context: .
        dockerfile: .docker/jira-node-server.dockerfile
      ports:
      - "3001:3001"
      working_dir: /var/www/jira-node-server
      volumes: 
        - .:/var/www/jira-node-server

    jira-dotnetcore-api:
      container_name: jira-dotnetcore-api
      build: 
        context: .
        dockerfile: .docker/jira-dotnetcore-api.dockerfile
      ports:
      - "3002:3002"
      working_dir: /var/www/jira-dotnetcore-api
      
    jira-react-app:
      container_name: jira-react-app
      build: 
        context: .
        dockerfile: .docker/jira-react-app.dockerfile
      ports:
      - "3000:3000"
      working_dir: /var/www/jira-react-app
      volumes: 
        - .:/var/www/jira-react-app