version: "2"
 
services:
    dev-jira-react-app:
      container_name: dev-jira-react-app
      build: 
        context: ./Jira.ReactApp
        dockerfile: ./jira-react-app.dev.dockerfile
      ports:
        - "8000:3000"
      working_dir: /var/www/jira-react-app
      env_file:
        - ./Jira.ReactApp/jira-react-app.env
      volumes: 
        - ./Jira.ReactApp:/var/www/jira-react-app
      restart: always

    dev-jira-node-server:
      container_name: dev-jira-node-server
      build: 
        context: ./Jira.NodeServer
        dockerfile: ./jira-node-server.dev.dockerfile
      ports:
        - "8001:3001"
      working_dir: /var/www/jira-node-server
      env_file:
        - ./Jira.NodeServer/jira-node-server.env
      volumes: 
        - ./Jira.NodeServer:/var/www/jira-node-server
      restart: always

    dev-jira-dotnetcore-api:
      container_name: dev-jira-dotnetcore-api
      build: 
        context: ./Jira.Api
        dockerfile: ./jira-dotnetcore-api.dev.dockerfile
      ports:
        - "8002:3002"
      working_dir: /var/www/jira-dotnetcore-api
      env_file:
        - ./Jira.Api/jira-dotnetcore-api.env
      restart: always