version: "2"
 
services:      
    jira-react-app:
      container_name: jira-react-app
      build: 
        context: ./Jira.ReactApp
        dockerfile: ./jira-react-app.dockerfile
      ports:
        - "3000:3000"
      restart: always

    jira-node-server:
      container_name: jira-node-server
      build: 
        context: ./Jira.NodeServer
        dockerfile: ./jira-node-server.dockerfile
      ports:
        - "3001:3001"
      restart: always

    jira-dotnetcore-api:
      container_name: jira-dotnetcore-api
      build: 
        context: ./Jira.Api
        dockerfile: ./jira-dotnetcore-api.dockerfile
      ports:
        - "3002:3002"
      restart: always